# Generated by Django 3.2.4 on 2023-10-27 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('messageid', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=250)),
                ('sender', models.CharField(max_length=200, null=True)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('recieve_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='single_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.TextField()),
                ('channel_status', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('channel_for_RM_chat', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='chat_user',
            fields=[
                ('chatuserid', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.TextField()),
                ('channel_status', models.BooleanField(default=False)),
                ('RM', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(auto_now_add=True, null=True)),
                ('orderid', models.ForeignKey(db_column='orderid', on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.orders')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
