# Generated by Django 3.2.4 on 2023-10-27 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RMsReview',
            fields=[
                ('rmsreviewid', models.AutoField(primary_key=True, serialize=False)),
                ('review_message', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(default=1)),
                ('isapproved', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('approveuserid', models.ForeignKey(blank=True, db_column='approveuserid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approveid', to=settings.AUTH_USER_MODEL)),
                ('clientid', models.ForeignKey(db_column='clientid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('rmid', models.ForeignKey(db_column='rmid', on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.rmsettings', to_field='rmid')),
            ],
        ),
    ]
