# Generated by Django 3.2.4 on 2023-10-27 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UTMDetails',
            fields=[
                ('utm_source', models.CharField(blank=True, default='other', max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, default='other', max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, default='other', max_length=100, null=True)),
                ('utm_reference', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserReferral',
            fields=[
                ('referral_id', models.CharField(default='12345', max_length=100)),
                ('successful_referral_count', models.IntegerField(default=0)),
                ('potential_referral_count', models.IntegerField(default=0)),
                ('potential_referral_count_detail', models.JSONField(default=dict)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appliedcandidates',
            fields=[
                ('appliedcandidateid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.TextField(blank=True, null=True)),
                ('lastname', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='appliedresume/')),
                ('creationdate', models.DateField(auto_now=True)),
                ('jobhiringid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.jobhiring')),
            ],
        ),
    ]
