# Generated by Django 3.2.4 on 2023-10-27 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripepayments',
            fields=[
                ('stripepaymentsid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Seller_Message', models.TextField(blank=True, null=True)),
                ('Created', models.TextField(blank=True, null=True)),
                ('Amount', models.TextField(blank=True, null=True)),
                ('Amount_Refunded', models.TextField(blank=True, null=True)),
                ('Currency', models.TextField(blank=True, null=True)),
                ('Converted_Amount', models.TextField(blank=True, null=True)),
                ('Converted_Amount_Refunded', models.TextField(blank=True, null=True)),
                ('Fee', models.TextField(blank=True, null=True)),
                ('Tax', models.TextField(blank=True, null=True)),
                ('Converted_Currency', models.TextField(blank=True, null=True)),
                ('Mode', models.TextField(blank=True, null=True)),
                ('Status', models.TextField(blank=True, null=True)),
                ('Statement_Descriptor', models.TextField(blank=True, null=True)),
                ('Captured', models.TextField(blank=True, null=True)),
                ('Card_ID', models.TextField(blank=True, null=True)),
                ('Card_Last4', models.TextField(blank=True, null=True)),
                ('Card_Brand', models.TextField(blank=True, null=True)),
                ('Card_Funding', models.TextField(blank=True, null=True)),
                ('Card_Exp_Month', models.TextField(blank=True, null=True)),
                ('Card_Exp_Year', models.TextField(blank=True, null=True)),
                ('Card_Name', models.TextField(blank=True, null=True)),
                ('Card_Address_Country', models.TextField(blank=True, null=True)),
                ('Card_Issue_Country', models.TextField(blank=True, null=True)),
                ('Card_Fingerprint', models.TextField(blank=True, null=True)),
                ('Card_CVC_Status', models.TextField(blank=True, null=True)),
                ('Disputed_Amount', models.TextField(blank=True, null=True)),
                ('Dispute_Status', models.TextField(blank=True, null=True)),
                ('Dispute_Reason', models.TextField(blank=True, null=True)),
                ('Dispute_Date', models.TextField(blank=True, null=True)),
                ('Dispute_Evidence_Due', models.TextField(blank=True, null=True)),
                ('Payment_Source_Type', models.TextField(blank=True, null=True)),
                ('Is_Link', models.TextField(blank=True, null=True)),
                ('Destination', models.TextField(blank=True, null=True)),
                ('Transfer', models.TextField(blank=True, null=True)),
                ('Transfer_Group', models.TextField(blank=True, null=True)),
                ('PaymentIntent_ID', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webhookfullresponse',
            fields=[
                ('webhookfullresponseid', models.AutoField(primary_key=True, serialize=False)),
                ('json_response', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientWithdrawalRequest',
            fields=[
                ('withdrawalrequestid', models.AutoField(primary_key=True, serialize=False)),
                ('creationdate', models.DateTimeField(auto_now=True)),
                ('requested_currency', models.TextField()),
                ('requested_method', models.TextField()),
                ('requested_amount', models.FloatField()),
                ('isrefund_balance', models.BooleanField(default=False)),
                ('isrefund_hold', models.BooleanField(default=False)),
                ('rm_action', models.BooleanField(default=False)),
                ('accountant_action', models.BooleanField(default=False)),
                ('transaction_amount', models.FloatField(default=0)),
                ('transaction_screenshot', models.ImageField(blank=True, null=True, upload_to='transactionscreenshots/')),
                ('assigned_accountant', models.ForeignKey(blank=True, db_column='assigned_account', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='withdrawalrequest_assigned_account', to=settings.AUTH_USER_MODEL)),
                ('assigned_rm', models.ForeignKey(blank=True, db_column='assigned_rm', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='withdrawalrequest_assigned_rm', to=settings.AUTH_USER_MODEL)),
                ('clientid', models.ForeignKey(db_column='clientid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPayoutHistory',
            fields=[
                ('payouthistoryid', models.AutoField(primary_key=True, serialize=False)),
                ('creationdate', models.DateTimeField(auto_now=True)),
                ('wallet_transaction_amount', models.FloatField(default=0)),
                ('requested_currency', models.TextField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('isrefund_balance', models.BooleanField(default=False)),
                ('isrefund_hold', models.BooleanField(default=False)),
                ('clientid', models.ForeignKey(db_column='clientid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('paymentid', models.ForeignKey(blank=True, db_column='paymentid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.payments')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPayout',
            fields=[
                ('payoutid', models.AutoField(primary_key=True, serialize=False)),
                ('remaining_balance_bank', models.FloatField(blank=True, null=True)),
                ('successful_withdrawal_bank', models.FloatField(blank=True, null=True)),
                ('hold_bank', models.FloatField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('is_wallet_used_with_payment_gateway', models.BooleanField(default=False)),
                ('clientid', models.OneToOneField(db_column='clientid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
