# Generated by Django 3.2.4 on 2023-10-27 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserOffer',
            fields=[
                ('offerid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('server_ip', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('productlink', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('approvedrate', models.FloatField(blank=True, null=True)),
                ('payout', models.FloatField(blank=True, null=True)),
                ('platform_margin', models.FloatField(default=10)),
                ('affiliate_payout', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('creationdate', models.DateTimeField(auto_now=True)),
                ('isapproved', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='affiliatemedia/')),
                ('isremoved', models.BooleanField(default=False)),
                ('rmid', models.ForeignKey(db_column='rmid', default=103856, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.rmsettings', to_field='rmid')),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.agencysettings', to_field='asettingsuserid')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertiserOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now=True)),
                ('uuid', models.TextField(blank=True, null=True)),
                ('utm_source', models.TextField(blank=True, null=True)),
                ('utm_affiliate_id', models.TextField(blank=True, null=True)),
                ('utm_offerid', models.TextField(blank=True, null=True)),
                ('utm_productname', models.TextField(blank=True, null=True)),
                ('campaingname', models.TextField(blank=True, null=True)),
                ('payout', models.FloatField(blank=True, null=True)),
                ('affiliate_payout', models.FloatField(blank=True, null=True)),
                ('server_ip', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostbackWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RmAdvertiserOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RmAffiliateBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RmAffiliatePendingPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RmAffiliateOfferApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productlink_updatedutm', models.TextField(blank=True, null=True)),
                ('productlink_updatedutm_newdomain', models.TextField(blank=True, null=True)),
                ('click_count', models.IntegerField(blank=True, null=True)),
                ('traffic_source', models.TextField(blank=True, null=True)),
                ('expected_volume_of_leads', models.IntegerField(blank=True, null=True)),
                ('optional_message', models.TextField(blank=True, null=True)),
                ('isapproved', models.BooleanField(default=False)),
                ('affiliateid', models.ForeignKey(blank=True, db_column='affiliateid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('offerid', models.ForeignKey(blank=True, db_column='offerid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliates.advertiseroffer')),
                ('rmid', models.ForeignKey(blank=True, db_column='rmid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.rmsettings')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformPayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now=True)),
                ('rm_action', models.BooleanField(default=False)),
                ('account_action', models.BooleanField(default=False)),
                ('for_offer_id', models.TextField(blank=True, null=True)),
                ('productname', models.TextField(blank=True, null=True)),
                ('requested_method', models.TextField(blank=True, null=True)),
                ('requested_amount', models.FloatField(blank=True, null=True)),
                ('remaining_balance_on_dateofrequest', models.FloatField(blank=True, null=True)),
                ('transaction_amount', models.FloatField(default=0)),
                ('transaction_screenshot', models.ImageField(blank=True, null=True, upload_to='affiliatemedia/')),
                ('advertiser_action', models.BooleanField(default=False)),
                ('isremoved', models.BooleanField(default=False)),
                ('advertiserid', models.ForeignKey(blank=True, db_column='advertiserid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PlatformPayoutRequest_advertiserid', to=settings.AUTH_USER_MODEL)),
                ('assigned_account', models.ForeignKey(blank=True, db_column='assigned_account', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PlatformPayoutRequest_assigned_account', to=settings.AUTH_USER_MODEL)),
                ('assigned_rm', models.ForeignKey(blank=True, db_column='assigned_rm', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PlatformPayoutRequest_assigned_rm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerid', models.TextField(blank=True, null=True)),
                ('successful_withdrawal_bank', models.FloatField(default=0)),
                ('hold_bank', models.FloatField(default=0)),
                ('successful_withdrawal_usdt', models.FloatField(default=0)),
                ('hold_usdt', models.FloatField(default=0)),
                ('successful_withdrawal_btc', models.FloatField(default=0)),
                ('hold_btc', models.FloatField(default=0)),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.agencysettings', to_field='asettingsuserid')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliatePayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now=True)),
                ('requested_currency', models.TextField()),
                ('requested_method', models.TextField(blank=True, null=True)),
                ('requested_amount', models.FloatField(blank=True, null=True)),
                ('rm_action', models.BooleanField(default=False)),
                ('transaction_amount', models.FloatField(default=0)),
                ('transaction_screenshot', models.ImageField(blank=True, null=True, upload_to='affiliatemedia/')),
                ('account_action', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('affiliateid', models.ForeignKey(blank=True, db_column='affiliateid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='AffiliatePayoutRequest_affiliateid', to=settings.AUTH_USER_MODEL)),
                ('assigned_account', models.ForeignKey(blank=True, db_column='assigned_account', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='AffiliatePayoutRequest_assigned_account', to=settings.AUTH_USER_MODEL)),
                ('assigned_rm', models.ForeignKey(blank=True, db_column='assigned_rm', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='AffiliatePayoutRequest_assigned_rm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliatePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_balance_bank', models.FloatField(blank=True, null=True)),
                ('successful_withdrawal_bank', models.FloatField(blank=True, null=True)),
                ('hold_bank', models.FloatField(blank=True, null=True)),
                ('remaining_balance_usdt', models.FloatField(blank=True, null=True)),
                ('successful_withdrawal_usdt', models.FloatField(blank=True, null=True)),
                ('hold_usdt', models.FloatField(blank=True, null=True)),
                ('remaining_balance_btc', models.FloatField(blank=True, null=True)),
                ('successful_withdrawal_btc', models.FloatField(blank=True, null=True)),
                ('hold_btc', models.FloatField(blank=True, null=True)),
                ('affiliateid', models.ForeignKey(blank=True, db_column='affiliateid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.TextField(blank=True, null=True)),
                ('upi_address', models.TextField(blank=True, null=True)),
                ('upi_address_isverified', models.BooleanField(default=False)),
                ('usdt_address', models.TextField(blank=True, null=True)),
                ('btc_address', models.TextField(blank=True, null=True)),
                ('account_holder_name', models.TextField(blank=True, null=True)),
                ('account_no', models.TextField(blank=True, null=True)),
                ('bank_name', models.TextField(blank=True, null=True)),
                ('branch_ifsc_code', models.TextField(blank=True, null=True)),
                ('pancard_taxid', models.ImageField(upload_to='')),
                ('pancard_taxid_isverified', models.BooleanField(default=False)),
                ('adhaarcard_drivinglicence', models.ImageField(upload_to='')),
                ('adhaarcard_drivinglicence_isverified', models.BooleanField(default=False)),
                ('cancelled_cheque', models.ImageField(upload_to='')),
                ('cancelled_cheque_isverified', models.BooleanField(default=False)),
                ('passport_copy', models.ImageField(upload_to='')),
                ('passport_copy_isverified', models.BooleanField(default=False)),
                ('clientid', models.ForeignKey(blank=True, db_column='clientid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertiserWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.TextField(blank=True, null=True)),
                ('payment_method', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('for_offersids', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='affiliates.advertiseroffer')),
                ('request_from_rm', models.ForeignKey(blank=True, db_column='request_from_rm', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.rmsettings', to_field='rmid')),
            ],
        ),
    ]
