# Generated by Django 3.2.4 on 2023-09-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsedJWT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.TextField(unique=True)),
                ('count_used', models.IntegerField(default=0)),
            ],
        ),
    ]
