# Generated by Django 3.2.4 on 2023-09-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsedJWT',
            new_name='UsedJWToken',
        ),
    ]
