# Generated by Django 3.2.4 on 2023-09-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_login', '0002_rename_usedjwt_usedjwtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedjwtoken',
            name='count_used',
            field=models.BooleanField(default=False),
        ),
    ]
