# Generated by Django 3.2.4 on 2023-09-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_login', '0003_alter_usedjwtoken_count_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedjwtoken',
            old_name='count_used',
            new_name='status',
        ),
    ]
