# Generated by Django 3.2.4 on 2023-09-21 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whatsapp_login', '0004_rename_count_used_usedjwtoken_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whatsappuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.TextField()),
                ('secret_id', models.TextField()),
                ('clientid', models.OneToOneField(db_column='clientid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
