# Generated by Django 3.2.4 on 2023-09-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_login', '0006_alter_whatsappuser_clientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedjwtoken',
            name='status',
            field=models.BooleanField(),
        ),
    ]
