# Generated by Django 3.2.4 on 2023-10-27 04:05

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutselected',
            fields=[
                ('aboutselectedid', models.AutoField(primary_key=True, serialize=False)),
                ('abouttext', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('selectid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gigsselected',
            fields=[
                ('gigsselectedid', models.AutoField(primary_key=True, serialize=False)),
                ('gigtext', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shortdesselected',
            fields=[
                ('shortdesselectedid', models.AutoField(primary_key=True, serialize=False)),
                ('shortdestext', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('selectid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webstoryfiles',
            fields=[
                ('webstoryfilesid', models.AutoField(primary_key=True, serialize=False)),
                ('webstoryfiles', models.FileField(upload_to='webstories/')),
            ],
        ),
        migrations.CreateModel(
            name='Whychooseselected',
            fields=[
                ('whychooseselectedid', models.AutoField(primary_key=True, serialize=False)),
                ('choosetext', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('selectid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webstory',
            fields=[
                ('webstoryid', models.AutoField(primary_key=True, serialize=False)),
                ('title', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('filesid', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('caption', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('date', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='')),
                ('thumnailtitle', models.TextField(blank=True, null=True, unique=True)),
                ('isapproved', models.BooleanField(default=False)),
                ('aprovedby', models.ForeignKey(blank=True, db_column='aprovedby', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approvedby', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topinfluencer',
            fields=[
                ('topinfluencerid', models.AutoField(primary_key=True, serialize=False)),
                ('ordercompleteioncount', models.BigIntegerField(default=0)),
                ('influencerid', models.OneToOneField(db_column='influencerid', on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.influencersettings', to_field='influencer_userid')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleCompletionTasks',
            fields=[
                ('schedulecompletiontaskid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('comptask', models.BooleanField(default=False)),
                ('orderid', models.ForeignKey(blank=True, db_column='orderid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='OrderResponse',
            fields=[
                ('orderresponseid', models.AutoField(primary_key=True, serialize=False)),
                ('ordersummary', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('orderid', models.ForeignKey(blank=True, db_column='orderid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.orders')),
                ('videoid', models.ForeignKey(blank=True, db_column='videoid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.videos')),
                ('videolink', models.ForeignKey(blank=True, db_column='videolinkid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.videoslink')),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerSeoSettings',
            fields=[
                ('influencer_seo_settingsid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('influencer_userid', models.OneToOneField(blank=True, db_column='influencerid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.influencerprofile', to_field='influencer_userid')),
            ],
        ),
        migrations.CreateModel(
            name='Defaulttimezoneinfluencer',
            fields=[
                ('defaulttimezoneinfluencerid', models.AutoField(primary_key=True, serialize=False)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('userid', models.OneToOneField(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultRM',
            fields=[
                ('defaultrmid', models.AutoField(primary_key=True, serialize=False)),
                ('userassignedcount', models.BigIntegerField(default=0)),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultManager',
            fields=[
                ('defaultmanagerid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
