# Generated by Django 3.2.4 on 2023-08-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotificationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendNotificationtoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('title', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
