# Generated by Django 3.2.4 on 2023-10-27 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='zoomtoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='zoomeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_link', models.TextField()),
                ('meet_id', models.TextField()),
                ('meet_password', models.TextField()),
                ('schedule_date', models.DateTimeField(auto_now_add=True)),
                ('ismeetingend', models.BooleanField(default=False)),
                ('islinksent', models.BooleanField(default=False)),
                ('orderid', models.ForeignKey(db_column='orderid', on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.orders')),
            ],
        ),
    ]
