# Generated by Django 3.2.4 on 2023-10-27 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='accountsnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BrandOrAgencynotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='clientnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='influencernotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KYCnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='managernotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RMnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('slotnotisendstatus', models.BooleanField(default=False)),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
