# Generated by Django 3.2.4 on 2023-08-05 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inappnotifications', '0002_alter_notification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_link',
            field=models.TextField(default=datetime.datetime(2023, 8, 5, 10, 31, 43, 603039, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
