# Generated by Django 3.2.4 on 2023-08-06 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inappnotifications', '0003_auto_20230805_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.TextField(default=datetime.datetime(2023, 8, 6, 10, 52, 56, 199373, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
