# Generated by Django 3.2.4 on 2023-08-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inappnotifications', '0005_alter_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountsnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BrandOrAgencynotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='clientnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='influencernotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='kycwalanotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='managernotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RMnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('redirect_link', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
    ]
