# Generated by Django 3.2.4 on 2023-09-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inappnotifications', '0010_telegramnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramnotification',
            old_name='channel_id',
            new_name='chat_id',
        ),
    ]
