# Generated by Django 3.2.4 on 2023-09-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inappnotifications', '0011_rename_channel_id_telegramnotification_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramnotification',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
