# Generated by Django 3.2.4 on 2023-05-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='pdf_documents/')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('data', models.CharField(max_length=255)),
            ],
        ),
    ]
